// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5a8u2L7XtIFDeUEuE4mZM5yswuwNtzF0',
    appId: '1:1032543166438:web:a9e25ab38850add2ce8027',
    messagingSenderId: '1032543166438',
    projectId: 'adoppi',
    authDomain: 'adoppi.firebaseapp.com',
    storageBucket: 'adoppi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSXT1xwL7MlLLBTgEJF7P8-lAFKYyeKJk',
    appId: '1:1032543166438:android:7ad714aeeff5e204ce8027',
    messagingSenderId: '1032543166438',
    projectId: 'adoppi',
    storageBucket: 'adoppi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdH60F5fPZNihT5AbZaoVjFYNfc__rARI',
    appId: '1:1032543166438:ios:a301fce4822b84a1ce8027',
    messagingSenderId: '1032543166438',
    projectId: 'adoppi',
    storageBucket: 'adoppi.firebasestorage.app',
    iosBundleId: 'com.example.adoppi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdH60F5fPZNihT5AbZaoVjFYNfc__rARI',
    appId: '1:1032543166438:ios:a301fce4822b84a1ce8027',
    messagingSenderId: '1032543166438',
    projectId: 'adoppi',
    storageBucket: 'adoppi.firebasestorage.app',
    iosBundleId: 'com.example.adoppi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5a8u2L7XtIFDeUEuE4mZM5yswuwNtzF0',
    appId: '1:1032543166438:web:4a2e414f9ab5ea4fce8027',
    messagingSenderId: '1032543166438',
    projectId: 'adoppi',
    authDomain: 'adoppi.firebaseapp.com',
    storageBucket: 'adoppi.firebasestorage.app',
  );
}
